# Generated by Django 3.1.2 on 2022-05-17 17:17

import cpf_field.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recrutador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('scholarity', models.CharField(max_length=50)),
                ('cpf', cpf_field.models.CPFField(max_length=14, verbose_name='cpf')),
                ('telephone_number', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('numero_usuario', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('document', models.FileField(null=True, upload_to='pdfs')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('vaga_id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=1000)),
                ('salario', models.FloatField()),
                ('empresa', models.CharField(max_length=50)),
                ('modalidade', models.CharField(choices=[('PRESENCIAL', 'presencial'), ('REMOTO', 'home-office')], max_length=20)),
                ('local', models.CharField(max_length=20)),
                ('tipo_contratacao', models.CharField(choices=[('EST', 'Estagio'), ('CLT', 'Empregado registrado pela CLT'), ('PJ', 'Pessoa Jurídica')], max_length=3)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tecnologias', models.ManyToManyField(to='app_site.Tecnologia')),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_site.vacancies', verbose_name='Empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_site.user', verbose_name='Usuario')),
            ],
        ),
    ]
