# Generated by Django 3.1.2 on 2022-05-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='vaga_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
